version: '3'
services:
  webserver:
    build: node
    image: node-express-dev:1.0
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./work:/usr/var/app
    ports:
      - "8080:8080"
      - "3000:3000"
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/conf.d
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: phpymyadmin_app
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql_db
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8081:80